#### Ответ

*Обработка ошибок в промисах* осуществляется с помощью метода `catch`, который добавляет колбек-функцию для обработки возникших ошибок в промисе.

Метод `catch` принимает один аргумент - колбек-функцию, которая будет вызвана в случае, если промис перейдет в состояние отклонено (rejected). Колбек-функция принимает один аргумент - объект ошибки, который был возвращен в промисе.

Пример использования метода `catch`:

```javascript
promise.then(function(result) {
  // обработка успешного выполнения
}).catch(function(error) {
  // обработка ошибки
});
```

Если промис переходит в состояние отклонено, вызывается колбек-функция, переданная в метод `catch`. Эта функция может выполнять любые действия для обработки ошибки, например, выводить сообщение об ошибке в консоль или отправлять отчет об ошибке на сервер.

Кроме того, можно использовать метод `then` для обработки ошибок. Для этого нужно передать второй аргумент в метод `then`, который является колбек-функцией для обработки ошибки:

```javascript
promise.then(function(result) {
  // обработка успешного выполнения
}, function(error) {
  // обработка ошибки
});
```

Этот подход похож на использование метода `catch`, но имеет некоторые ограничения. Например, если ошибка возникает внутри метода `then`, то ее нельзя обработать с помощью второго аргумента метода `then`, и нужно использовать метод `catch`.

В целом, обработка ошибок в промисах производится с помощью метода `catch`, который позволяет легко и эффективно обрабатывать ошибки в асинхронном коде.

Подробнее: [[1.3.3 Promise. Обработка ошибок|Обработка ошибок в Promise]]

___
 #JavaScript #promise #catch #then #асинхронность 

___

### [[003 JSCore|Назад]]