#### Ответ

Когда возникает ошибка, JavaScript генерирует объект, содержащий её детали. 

Затем этот объект передаётся как аргумент в блок `catch`:

~~~javascript
try {   // ... 
} catch(err) { // <-- объект ошибки, можно использовать другое название вместо err   // ... }`
~~~

Для всех встроенных ошибок этот объект имеет два основных свойства:
`name` Имя ошибки. Например, для неопределённой переменной это `"ReferenceError"`.
`message` Текстовое сообщение о деталях ошибки.

___
 #JavaScript #try-catch #catch

___

### [[003 JSCore|Назад]]